desc emp;
select * from emp;
insert into dept value(443,"홍길동","서울");
insert into emp value(2,"홍길동","과장",1, 030124, 200, 50, 444);
delete from emp;
delete from dept;
desc course;
desc student;
insert into dept values(10, "경리부", "서울");
insert into dept values(20, "영업부", "경기");
insert into dept values(30, "영업부", "경기");
select * from dept;
update dept set loc ='서울' where deptno = 20;
rollback;
update dept set dname = '영업부' where dname = '총무부';
delete from dept where deptno = 30;
commit;
select@@autocommit;
set autocommit=0;